### ISSUE TITLE
Scope of the registry and contribution guide

### ISSUE THREAD

**Issue by muffato** [singularityhub/shpc-registry#11] opened 2022-08-30 09:07 UTC
Hi !
I'd like to clarify what the scope of this registry is and the requirements of container.yaml, to define when/if groups can contribute recipes back to it, as well as the expected maintenance process. To kick off the discussion, here are some ideas.

For instance, can we say that these fields are mandatory:

- url
- maintainer
- description

And whoever is listed as a maintainer can expect to be have PRs on this container.yaml to be assigned to them for review ?

About the list of tags, some groups may want to keep multiple patch versions of a software, which is not what the default `shpc update` looks for. Are groups free to push all the versions they want ?

About "latest", I'd propose to disallow `latest`, `stable`, etc from the list of tags, and they could easily move onto another version. And then, regarding the `latest` section, does it really have to be latest tag from the `tags:` section ? I expect cases where the community still considers say 2.4 as the default version, even though 3.0 is out.

And of course, institute/group-specific settings (in `env:` or the wrapper scripts) are not allowed.

Thanks,
Matthieu

**Comment by vsoch** [comment] 2022-08-30 09:49
Hi @muffato ! Yes, this is the main registry for the shpc software - it is largely open to contribution from any user/group to add scientific software. There is an automated monthly release, with tag named based on YYYY-MM, and a monthly update of container tags and corresponding digests.

> For instance, can we say that these fields are mandatory:

Yes, I consider these mandatory.

> And whoever is listed as a maintainer can expect to be have PRs on this container.yaml to be assigned to them for review ?

If that happens the maintainer can be pinged, however given the automation I think it unlikely, for the most part. But generally, yes.

> About the list of tags, some groups may want to keep multiple patch versions of a software, which is not what the default shpc update looks for. Are groups free to push all the versions they want ?

I don't see why not! Most containers have many versions. We probably do eventually want to decide at one point is a version deprecated or removed - e.g., I can imagine these container.yaml files getting very large.

> About "latest", I'd propose to disallow latest, stable, etc from the list of tags, and they could easily move onto another version.

Any particular reason why? If we keep the digest (which we use to pull) it's just another string. I ask because some containers only have a latest.

> And then, regarding the latest section, does it really have to be latest tag from the tags: section ? I expect cases where the community still considers say 2.4 as the default version, even though 3.0 is out.

Hmm that is a good point - latest != default. We keep a "latest" because if someone installs a random container, we generally want to give them a more recent version. It's easy to automate that (and it's done with shpc update). If we add an opinion to the mix I'm not sure how to make that decision. But perhaps there could be a container.yaml flag/mode that says "don't automatically update me" and then someone decides they are responsible for it? 

> And of course, institute/group-specific settings (in env: or the wrapper scripts) are not allowed.

I think general supporting overlay files that have some meaningful sets of env/wrapper scripts, etc., would be OK. Probably the line that would be crossed is a hard coded path for a specific cluster setup that couldn't be useful beyond that cluster.

**Comment by muffato** [comment] 2022-08-30 21:12
> > About the list of tags, some groups may want to keep multiple patch versions of a software, which is not what the default shpc update looks for. Are groups free to push all the versions they want ?
> 
> I don't see why not! Most containers have many versions. We probably do eventually want to decide at one point is a version deprecated or removed - e.g., I can imagine these container.yaml files getting very large.

Does the automatic updater remove versions on its own ?

> > About "latest", I'd propose to disallow latest, stable, etc from the list of tags, and they could easily move onto another version.
> 
> Any particular reason why? If we keep the digest (which we use to pull) it's just another string. I ask because some containers only have a latest.

What happens if the checksum doesn't match: shpc refuses to install the aliases ?

Right, I was indeed assuming that the software would also have versions that point to the same container. One important feature of containers and shpc is reproducibility, and it's true that the "latest" tag of most containers is not helping that. Rather than a hard rule, could we make it a _guideline_ that container.yaml should only list actual versions if possible ?

> that is a good point - latest != default. (...) It's easy to automate that (and it's done with shpc update). If we add an opinion to the mix I'm not sure how to make that decision. But perhaps there could be a container.yaml flag/mode that says "don't automatically update me" and then someone decides they are responsible for it?

To clarify, you mean that the default version shpc will install is not necessarily the container tag named `latest`, nor it is the most recent container (by release date / version ordering), right ?
Then, to remove the ambiguity, maybe the section in `container.yaml` should be called `default_tag` ? By the way, I've always wondered why there is a checksum in the `latest:` section, cf https://github.com/singularityhub/shpc-registry/blob/main/quay.io/biocontainers/samtools/container.yaml#L5-L6 . In my mind, it should be `default_tag: 1.15--h3843a85_0`, with the tag having to be present in `tags:` as well.

> > And of course, institute/group-specific settings (in env: or the wrapper scripts) are not allowed.
> 
> I think general supporting overlay files that have some meaningful sets of env/wrapper scripts, etc., would be OK. Probably the line that would be crossed is a hard coded path for a specific cluster setup that couldn't be useful beyond that cluster

Agree on the red-line. Do you have an example of what that acceptable use would be ? I don't get it yet 🐌 

Another point that comes from https://github.com/singularityhub/singularity-hpc/issues/578
The rule is that this registry skips the docker.io namespace, and if anyone makes a PR with docker.io they'll be asked to rename it ?

Finally, I think this rules, guidelines, policies, need to be written somewhere as it will be relevant for groups who want to use shpc and need to decide what registry to use. In README.md ?

**Comment by vsoch** [comment] 2022-08-30 21:29
> Does the automatic updater remove versions on its own ?

No, absolutely not! For the time being I care about reproducibility, so I don't want to remove a version of something someone was using.

> What happens if the checksum doesn't match: shpc refuses to install the aliases ?

The pull is of the checksum directly, so it's more of a "does it still exist" vs not. We would want to rely on the underlying container technology to do any kind of validation, and the various tools have different ways to do that (e.g., signatures). I think as the sbom / security landscape gets better in tooling this can be something we add.

> Right, I was indeed assuming that the software would also have versions that point to the same container. One important feature of containers and shpc is reproducibility, and it's true that the "latest" tag of most containers is not helping that. Rather than a hard rule, could we make it a guideline that container.yaml should only list actual versions if possible ?

Absolutely, if possible. Shpc is always going to be able to present a concept of "latest" as the latest tag, as many users/admins want that.

> To clarify, you mean that the default version shpc will install is not necessarily the container tag named latest, nor it is the most recent container (by release date / version ordering), right ?

Right, the "latest" concept of shpc typically points to a version. E.g., if I just install `autamus/clingo`, the "latest" tag points me to 5.5.1.

https://github.com/singularityhub/shpc-registry/blob/d939177b08293af1dcb622d9fd4b93c3081b0178/ghcr.io/autamus/clingo/container.yaml#L5-L6

You'll also notice that container doesn't have a "latest" tag, and that's typically my preference unless it's unavoidable (e.g., vanessa/salad my testing container never gets updated, but just has latest).

> Then, to remove the ambiguity, maybe the section in container.yaml should be called default_tag ? 

We could make that change, but would it really be that helpful? It's only seen by a container.yaml developer, and it is in fact _is_ pointing to the latest tag. Perhaps a compromise would be to rename "latest" in the library.json and other exposed metadata to instead be default_tag? I'm hesitant to make big changes that will temporarily break things, but if this is important to you and others, I think we should.

> By the way, I've always wondered why there is a checksum in the latest: section, cf https://github.com/singularityhub/shpc-registry/blob/main/quay.io/biocontainers/samtools/container.yaml#L5-L6 . In my mind, it should be default_tag: 1.15--h3843a85_0, with the tag having to be present in tags: as well.

That just makes the design consistent so when we are installing (pulling) the tag we retrieve has the same structure as any other tag. Otherwise we'd need to look up latest and then index. It would be possible to change in shpc, but a lot of work to refactor in the recipes, and I'm not sure the time is worth the benefit.

> Agree on the red-line. Do you have an example of what that acceptable use would be ? I don't get it yet snail

If there was an environment variable like `MYCENTER_CUSTOM_PATH=/work/pathy/pancakes` that would cross the line. But anything generic (e.g., using a $HOME or similar) I think would be okay. This also makes me think perhaps we should have variables that indicate different locations in SHPC so they can be written into those areas (and used). E.g., people might install shpc / containers /modules to different places, but those variables are known when you run shpc. I think the best way to work on this would be to find an example that has some custom logic, and then develop the idea around that. I'd be happy to work on this with an example.

> The rule is that this registry skips the docker.io namespace, and if anyone makes a PR with docker.io they'll be asked to rename it ?

That's a good point. I think the main goal of the namespaces is to not conflict. So as long as there isn't a repository named docker.io (e.g., docker.io/docker.io) there shouldn't be conflicts. The reviewer could suggest moving it up one level, however, and would likely want to check that it isn't redundant with something in the root.

> Finally, I think this rules, guidelines, policies, need to be written somewhere as it will be relevant for groups who want to use shpc and need to decide what registry to use. In README.md ?

Totally agree! I was looking at our shpc docs (on readthedocs) and we have basic instructions for writing modules/container.yaml, but that's very different from a contributing guide. Is this something you would be interested in taking a first shot at? I'm thinking it could go in the root of shpc-registry, that way someone else making a registry can write their own guide. Then from shpc on readthedocs we'd want to make sure to clearly link to it. What do you think?

**Comment by muffato** [comment] 2022-09-08 15:50
(FYI I'm doing things on the codebase right now, but will come back to this right after. Happy to write things down in the README, though my style is way drier than yours ;) )

**Comment by vsoch** [comment] 2022-09-08 16:24
haha I think you're style is good too :) Thank you @muffato !

**Closed** 2022-09-20 12:43 UTC
